### ISSUE TITLE
example workingModel, seg fault on display_blocks.py

### ISSUE THREAD

**Issue by berndhahnebach** [anaiortega/XCmodels#1]
on display_blocks.py I get the following error:

``
$ python display_blocks.py 
WARNING:root:VectorFieldData.calculateLengths: no vectors defined.
Speicherzugriffsfehler
$

Speicherzugriffsfehler is German for Segmentation fault

**Comment by berndhahnebach** [comment]
same error on display_localAxes.py

**Comment by berndhahnebach** [comment]
same error on display_loads_beamEl.py


$ python display_loads_beamEl.py 
xcSet ((((((beamX+beamY)+columnZ)+wall)+foot)+decklv1)+decklv2)
QpntBeams
ERROR: In /work/standalone-x64-build/VTK-source/Common/Core/vtkLookupTable.cxx, line 143
vtkLookupTable (0x55c741240480): Bad table range: [1e+99, -1e+99]

WARNING:root:VectorFieldData.calculateLengths: no vectors defined.
Speicherzugriffsfehler

**Comment by lcpt** [comment]
This error has appeared with the migration from VTK 5 to VTK 6 this summer we'll fix that as soon as possible. It doesn't depends of the model, is a bug in the XC code.

**Comment by anaiortega** [comment]
This VTK6 migration guide can give us some clue to solve the problem (vtk data objects have changed)
https://www.vtk.org/Wiki/VTK/VTK_6_Migration_Guide

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/46571763-60faa700-c97b-11e8-91c6-b88134cec711.png)

![image](https://user-images.githubusercontent.com/12873038/46571763-60faa700-c97b-11e8-91c6-b88134cec711.png)

I've fixed both errors (the vectors were not added to the vtk container: it's strange, maybe it made a mistake when upgrading to VTK 6).

**Comment by lcpt** [comment]
I've fixed both errors (the vectors were not added to the vtk container: it's strange, maybe it made a mistake when upgrading to VTK 6).

![image](https://user-images.githubusercontent.com/12873038/46571849-a5d30d80-c97c-11e8-90a0-b0c95dbc1321.png)

![image](https://user-images.githubusercontent.com/12873038/46571853-ad92b200-c97c-11e8-8fec-945cb7c742a5.png)

**Comment by berndhahnebach** [comment]
works great here too
