### ISSUE TITLE
example workingModel, files missing

### ISSUE THREAD

**Issue by berndhahnebach** [anaiortega/XCmodels#2]
it seams to miss lots of moduls. For example if I try 

$ python display_normStrsULS.py

Traceback (most recent call last):
  File "display_normStrsULS.py", line 11, in <module>
    execfile(cfg.verifNormStrFile)
IOError: [Errno 2] No such file or directory: '/home/hugo/Documents/projekte--BIM--opendev/xc/XCmodels/workingModel/results/verifications/verifRsl_normStrsULS.py'

but there is no module verifRsl_normStrsULS.py  Non at all in the whole directory of workingModel. There is not even a directory /results/verifications/ butthis is defined in module env_config.py

**Comment by anaiortega** [comment]
verifRsl_normStrsULS.py is a file with results from the normal stress verification (we don't push result files to github). To obtain it, you must run these scripts in calculations directory:
assign_RCsections.py
calc_internalForces_ULS_SLS.py
verif_normStrsULS.py
(previously, results/internalForces and results/verifications directories must be created)

**Comment by berndhahnebach** [comment]
Cool it works. It is starting to make fun :-) It is cumbersome to rotate in the viewer. Do you know some resources about moving zooming etc by keyboard and mouse inside the Vtk openGL viewer?

**Comment by berndhahnebach** [comment]
But some new error a raised too ... 

``
$ python verif_normStrsULS.py 
XC::FiberSectionShear3d::GetInteractionDiagram; error in computation of interaction diagram (0.0265444) seems too big.
XC::FiberSectionShear3d::GetInteractionDiagram; error in computation of interaction diagram (0.0245419) seems too big.
XC::FiberSectionShear3d::GetInteractionDiagram; error in computation of interaction diagram (0.00512709) seems too big.
$ cd

**Comment by lcpt** [comment]
> Cool it works. It is starting to make fun :-) It is cumbersome to rotate in the viewer. Do you know some resources about moving zooming etc by keyboard and mouse inside the Vtk openGL viewer?

Not really, I've learned to use it by trial and error...

**Comment by lcpt** [comment]
> But some new error a raised too ...
> 
> ``
> $ python verif_normStrsULS.py
> XC::FiberSectionShear3d::GetInteractionDiagram; error in computation of interaction diagram (0.0265444) seems too big.
> XC::FiberSectionShear3d::GetInteractionDiagram; error in computation of interaction diagram (0.0245419) seems too big.
> XC::FiberSectionShear3d::GetInteractionDiagram; error in computation of interaction diagram (0.00512709) seems too big.
> $ cd

That's not very serious. To evaluate the quality of the computed interaction diagram, the program computes the capacity factor for all the points that define it (so in theory FC==1 for all of them). The error comes from floating point arithmetic and it's not easy to solve. The tolerance which triggers the error message is 0.005 maybe we must let the user specify this tolerance. Anyway the results are good enough (in this case errors are under 3 percent).
