### ISSUE TITLE
ps_bole_calculus error in mesh display

### ISSUE THREAD

**Issue by berndhahnebach** [anaiortega/XCmodels#7]
I get an error here ... 
https://github.com/anaiortega/XCmodels/blob/de71d9ab820d853b64d00cf6c4b0f3f80a13bc49/ps_bole_calculs_statiques/xc_model_impact/display_mesh.py#L12

`
 $ python display_mesh.py 
Traceback (most recent call last):
  File "display_mesh.py", line 11, in <module>
    defDisplay.FEmeshGraphic(xcSet= setToDisp,caption='',viewNm="-X+Y+Z",defFScale=1.0)
TypeError: FEmeshGraphic() got an unexpected keyword argument 'viewNm'
$ 
  `

this works but I am not sure if it is the right way to do it ... 

`defDisplay.displayMesh(xcSets= setToDisp,fName= None,caption='Mesh',nodeSize=0.020,scaleConstr=0.30)`

bernd

**Comment by lcpt** [comment]
The code was outdated. It has been fixed. Thanks Bernd!

Cheers Luis.
